config/routes.rb
Rails.application.routes.draw do
  root to: 'organizations#index'

  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/no_roles', to: 'user_sessions#no_roles', as: :no_roles

  resources :organizations do
    get :autocomplete_organization_name, :on => :collection, as: :autocomplete
  end

  resources :users do
    get :autocomplete_user_name, :on => :collection, as: :autocomplete
    member do
      get 'change_password'
      patch 'update_password'
      patch 'generate_api_token'
    end
  end

  post '/departments/select', to: 'departments#select', as: :departments_select
  put '/departments/paste', to: 'departments#paste', as: :departments_paste
  get '/departments/reset', to: 'departments#reset', as: :departments_reset

  resources :roles do
    get :autocomplete_role_name, :on => :collection, as: :autocomplete
  end

  resources :role_members
  patch(
    '/role_members',
    to: 'role_members#clone',
    as: :clone_roles
  )

  resources :rights
  resources :departments do
    get :autocomplete_department_id, :on => :collection, as: :autocomplete
  end
  resources :agreements do
    get :autocomplete_agreement_prop, :on => :collection, as: :autocomplete
  end

  post '/uploads', to: 'attached_files#create', as: :uploads # For upload images via CKEditor
  resources :attached_files, only: [:create, :show, :destroy] # For attach/download/delete files in record by user
  # Show image in article
  get(
    'articles/:id/files/:file_name',
    to: 'attached_files#download_image',
    as: :article_download_file,
    constraints: { file_name: /[^\/]*/ }
  )

  resources :versions, only: [:index]
  resources :agreement_kinds
  resources :organization_kinds
  post "versions/:id/revert" => "versions#revert", as: :revert_version
  get "/attachments/:id/download", to: "attachments#download", as: :attachment_download
  resources :tag_kinds
  resources :tags
  resources :tag_members, only: %i[create destroy]
  resources :incidents do
    get :autocomplete_inciden_name, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'incidents#search', via: [:get, :post], as: :search
    end
  end
  resources :link_kinds
  resources :links, only: %i[create destroy]
  resources :record_templates
  get "/reports/:name", to: 'reports#show', as: :reports
  post "/reports/:name", to: 'reports#show', as: :filtred_reports
  get "/commands/:name", to: 'commands#run', as: :commands
  #mount Blazer::Engine, at: "blazer"
  get "/dashboards/", to: 'dashboards#index', as: :dashboards
  get "/investigations_dashboard/", to: 'dashboards#investigations_dashboard', as: :investigations_dashboard
  get "/vulnerabilities_dashboard/", to: 'dashboards#vulnerabilities_dashboard', as: :vulnerabilities_dashboard
  get "/user_actions_dashboard/", to: 'dashboards#user_actions_dashboard', as: :user_actions_dashboard
  get "/dashboards/:name", to: 'dashboards#show', as: :dashboard
  get "/charts/:name", to: 'charts#show', as: :charts
  resources :hosts do
    get :autocomplete_host_name, :on => :collection, as: :autocomplete
    member do
      patch :toggle_readable
    end
    collection do
      match 'search' => 'hosts#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
  end

  resources :articles do
    get :autocomplete_article_name, :on => :collection, as: :autocomplete
    collection do
      patch :toggle_subscription
    end
    member do
      patch :publicate
    end
  end

  resources :articles_folders
  post(
    '/articles_folders_select',
    to: 'articles_folders#select',
    as: :articles_folders_select
  )
  put(
    '/articles_folders_paste',
    to: 'articles_folders#paste',
    as: :articles_folders_paste
  )
  get(
    '/articles_folders_reset',
    to: 'articles_folders#reset',
    as: :articles_folders_reset
  )

  get '/serach/index', to: 'search#index', as: :search
  resources :scan_options
  resources :scan_jobs do
    member do
      get 'run'
    end
  end
  resources :scan_results, only: [:index, :show, :search] do
    collection do
      get 'open_ports'
      get 'new_ports'
      match 'search' => 'scan_results#search', via: [:post, :get], as: :search
    end
  end
  resources :host_service_statuses
  resources :host_services
  get '/schedule/', to: 'schedules#show', as: :schedule
  get '/schedules/', to: 'schedules#index', as: :schedules
  post '/schedule/', to: 'schedules#update', as: :update_schedule
  get '/scheduled_jobs/', to: 'scheduled_jobs#index', as: :scheduled_jobs
  delete '/scheduled_jobs/', to: 'scheduled_jobs#destroy', as: :destroy_scheduled_jobs
  resources :scan_jobs_hosts, only: [:index, :create, :destroy]
  resources :scan_job_logs, only: [:index]
  resources :feeds
  resources :investigation_kinds
  resources :investigations do
    collection do
      match 'search' => 'investigations#search', via: [:get, :post], as: :search
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
      post :clone
    end
  end
  resources :indicators do
    collection do
      match 'search' => 'indicators#search', via: [:get, :post], as: :search
      get :tree_show
      post :select
      put :paste
      get :reset
    end
    member do
      patch :toggle_readable
      patch :toggle_purpose
      patch :toggle_trust_level
    end
  end
  resources :enrichments, only: [:index, :show, :create, :destroy]
  resources :indicator_contexts
  resources :vulnerabilities do
    get :autocomplete_vulnerability_codename, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'vulnerabilities#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
    member do
      patch :toggle_processed
      patch :toggle_custom_relevance
      patch :toggle_readable
    end
  end
  resources :custom_fields
  resources :delivery_lists
  resources :delivery_subjects, only: [:index, :create, :destroy] do
    collection do
      get 'list_subjects'
      post 'notify' => 'delivery_subjects#notify', via: [:get], as: :notify
    end
    member do
      patch :toggle_readable
    end
  end
  resources :delivery_recipients, only: [:index, :create, :destroy]
  resources :search_filters
  resources :vulnerability_kinds
  resources :vulnerability_bulletin_kinds
  resources :vulnerability_bulletins do
    collection do
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
    end
  end
  resources :vulnerability_bulletin_members, only: %i[index create destroy]
  resources :vulnerability_bulletin_statuses

  resources :user_actions, only: [:index, :show]

  post '/translatet', to: 'translate#show', as: :translate

  resources :notifications_logs, only: [:index]

  resources :selectors, only: [:index]

  patch(
    '/selectors',
    to: 'selectors#update',
    as: :toggle_selection
  )
  delete(
    '/reset_selections',
    to: 'selectors#destroy',
    as: :reset_selections
  )

  patch(
    '/toggle_processed_processing_logs',
    to: 'processing_logs#toggle_processed',
    as: :toggle_processed_processing_logs
  )

  resources :custom_reports
  resources :custom_reports_folders do
    collection do
      post :paste
    end
  end

  resources :custom_reports_results, only: [:index, :show, :new, :create, :destroy, :download] do
    member do
      get 'download'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :custom_reports_api, only: [:show]
      resources :ra_api, only: [:create]
    end
  end

  resources :agents

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminSidekiqWebConstraint.new
  require 'sidekiq/cron/web'

  # TODO: use or delete (it for routing error handling when api client used)
  # match '*path', to: "api/v1/routing_error#show", format: true, constraints: {format: :json}, defaults: {format: 'html'}, via: [:get, :post]
end

app/models/scan_job.rb
class ScanJob < ApplicationRecord
  include OrganizationMember
  include Linkable
  include Tagable
  include Attachable
  include Rightable

  SCAN_ENGINES = %w[nmap shodan]

  has_paper_trail

  attr_accessor :add_organization_hosts

  after_save :link_organization_hosts

  validates :name, length: { minimum: 3, maximum: 100 }
  validates :name, uniqueness: { scope: :organization_id }
  validates :scan_option_id, numericality: { only_integer: true }
  validates :agent_id, numericality: { only_integer: true, allow_blank: true }

  belongs_to :scan_option

  has_one :schedule, as: :job, dependent: :destroy

  has_many :scan_results, dependent: :delete_all

  has_many :scan_jobs_hosts, dependent: :delete_all
  has_many :linked_hosts, through: :scan_jobs_hosts, source: :host

  has_many :scan_job_logs, dependent: :delete_all

  belongs_to :agent, optional: true

  def self.scan_engines
    SCAN_ENGINES
  end

  def worker
    'NetScanJob'
  end

  def job_queue(queue = 'scheduled_scan')
    if scan_engine == 'shodan' && ENV['FREE_SHODAN'] == 'true'
      'free_shodan_scan'
    else
      "#{queue}_#{scan_option.queue_number}"
    end
  end

  def targets
    hosts_from_scan_job = hosts.split(',').map(&:strip)
    hosts_from_scan_job | linked_hosts.pluck(:ip).map(&:to_s)
  end

  # For send nmap options to nmap as string
  def nmap_options_string
    h = targets.join(' ')
    opt = scan_option.options.each_with_object([h.to_s]) do |(opt_key, opt_value), memo|
      if opt_key == 'top_ports' && opt_value.present?
        memo << "--top-ports #{opt_value}"
      elsif opt_key == 'ports' && opt_value.present? && ports.empty?
        memo << "-p #{ScanJob.normalize_ports_as_string(opt_value)}"
      elsif opt_value == '1' && ScanOption::NMAP_OPT_MAP[opt_key.to_sym]
        memo << ScanOption::NMAP_OPT_MAP[opt_key.to_sym]
      end
    end
    opt << "-p #{ScanJob.normalize_ports_as_string(ports)}" if ports.present?
    opt.join(' ')
  end

  def self.normalize_ports_as_array(ports)
    ports.split(',').map do |port|
      if port.include?('-')
        Range.new(*port.split('-').map(&:to_i))
      else
        port.to_i
      end
    end
  end

  def self.normalize_ports_as_string(ports)
    ports.delete(' ')
  end

  private

  def link_organization_hosts
    return if add_organization_hosts != '1'
    organization.hosts.each do |host|
      scan_jobs_host = ScanJobsHost.new(
        host_id: host.id,
        scan_job_id: id
      )
      scan_jobs_host.save
    end
  end
end

app/controllers/scan_jobs_controller.rb
# frozen_string_literal: true

class ScanJobsController < ApplicationController
  include RecordOfOrganization

  def run
    @record = record
    authorize @record
    active_job = NetScanJob.perform_later(
      @record.id,
      @record.job_queue('now_scan')
    )
    #protocol_action("scan started by #{@job.name}")
    redirect_to(
      session.delete(:edit_return_to),
      organization_id: @organization&.id,
      success: t('flashes.now_scan', net_scan_job_id: active_job.provider_job_id)
    )
  end

  private

  def model
    ScanJob
  end

  def records_includes
    %i[organization scan_option]
  end

  def preset_record
    return if params.blank?
    @record.hosts = params[:ip] if params[:ip].present?
    if params[:host_id].present?
      @record.hosts = Host.find(params[:host_id]).ip
    end
    @record.ports = params[:port_number] if params[:port_number].present?
    if params[:service].present?
      name = [params[:service]]
      name << @organization.name if @organization.present?
      @record.name = name.join(' ')
    end
  end
end

app/views/scan_jobs/_form.html.slim
.well
  = render 'form_errors', record: @record
  .row
    = form_for @record, html: {class: 'form-horizontal'} do |f|

      .form-group.required
        .field
          .col-lg-2.text-right
            = f.label :name, class: 'control-label'
          .col-lg-8
            = f.text_field :name, class: 'form-control'

      .form-group.required
        .field
          .col-lg-2.text-right
            = f.label :organization_id, class: 'control-label'
          .col-lg-8
            = autocomplete_field_tag :organization, '', autocomplete_organizations_path, id_element: '#scan_job_organization_id',  class: 'form-control', autocomplete: :off, value: (@record.organization&.name || @organization&.name), readonly: @organization&.id.present?
            = f.hidden_field :organization_id, value: @organization&.id || @record.organization_id

      .form-group.recomended
        .field
          .col-lg-2.text-right
            = f.label :scan_engine, class: 'control-label'
          .col-lg-8
            = f.select :scan_engine, ScanJob.scan_engines, {}, { class: 'form-control' }

      .form-group.recomended
        .field
          .col-lg-2.text-right
            = f.label :agent_id, class: 'control-label'
          .col-lg-8
            = f.collection_select :agent_id, Agent.all, :id, :name, { include_blank: true}, { class: 'form-control' }

      .form-group.recomended
        .field
          .col-lg-2.text-right
            = f.label :scan_option_id, class: 'control-label'
          .col-lg-8
            = f.collection_select :scan_option_id, ScanOption.all, :id, :name, {}, { class: 'form-control' }
      .form-group
        .field
          .col-lg-2.text-right
            = f.label :add_organization_hosts, class: 'control-label'
          .col-lg-8
            = f.check_box :add_organization_hosts, class: 'big-checkbox'

      .form-group
        .field
          .col-lg-2.text-right
            = f.label :hosts, class: 'control-label'
          .col-lg-8
            = f.text_field :hosts, class: 'form-control', placeholder: t('placeholders.scan_jobs.hosts')

      .form-group
        .field
          .col-lg-2.text-right
            = f.label :ports, class: 'control-label'
          .col-lg-8
            = f.text_field :ports, class: 'form-control'


      .form-group
        .field
          .col-lg-2.text-right
            = f.label :description, class: 'control-label'
          .col-lg-8
            = f.text_area :description, rows: 8, class: 'form-control'

      .actions.form-group
        .col-lg-offset-2.col-lg-8
          => f.submit t('helpers.submit.save'), class: 'btn btn-success'
          = render 'form_back_button'

app/views/scan_jobs/_record.html.slim
= show_for @record do |r|
  = r.show :name
  = r.show :organization_id
    = link_to @record.organization.name, @record.organization

  = r.show t('labels.scan_jobs.working_count')
    = link_to ScanJobDecorator.new(@record).show_working_count, scan_job_logs_path(job_id: record.id) 
  = r.show t('labels.scan_jobs.planned_count') do
    = link_to ScanJobDecorator.new(@record).show_planned_count, scheduled_jobs_path
  = r.show :scan_engine
  = r.show :scan_option_id do
    =link_to @record.scan_option.name, @record.scan_option
  = r.show :agent_id do
    - if @record&.agent.present?
      =link_to @record&.agent&.name, @record&.agent
  = r.show :hosts
  = r.show :ports
  = r.show :description

= render 'application/record_versions'
=> link_to run_scan_job_path(@record), class: 'btn btn-success' do
  = fa_icon 'search'
  =< t('views.action.scan')

app/views/scan_jobs/_records.html.slim
= index_search :name_or_organization_name_or_scan_engine_or_scan_option_name_or_agent_name_cont, organization_id_eq: @organization&.id
= command_button_for records, organization_id: @organization.id
= report_button_for @records, organization_id: @organization.id
= index_for records, decorator: ScanJobDecorator, actions: false do |t|
  - t.header attribute: :name, sort_by: :name, sort: :desc
  - t.header attribute: :scan_engine, sort_by: :scan_engine, sort: :desc
  - t.header attribute: :organization_id, sort_by: :organization_name, sort: :desc
  - t.header attribute: :scan_option_id, sort_by: :scan_option_name, sort: :desc
  - t.header attribute: :agent_id, sort_by: :agent_name, sort: :desc
  - t.header attribute: :scan_job_logs, label: t('labels.scan_jobs.working_planned_count')
  - t.header fit: true
  - t.field { |record| link_to record.name, record }
  - t.field { |record| link_to record.scan_engine, record }
  - t.field { |record| link_to record.organization.name, record.organization }
  - t.field { |record| link_to record.scan_option.name, record.scan_option}
  - t.field do |record|
    - if record&.agent.present?
      = link_to record&.agent&.name, record&.agent
  - t.field do |record|
    => link_to record.show_working_count, scan_job_logs_path(job_id: record.id)
    = record.show_separator
    =< link_to record.show_planned_count, scheduled_jobs_path
  - t.field do |record|
    => link_to run_scan_job_path(record), class: 'btn btn-link' do
      span.text-info
        = fa_icon 'search'
      =< t('views.action.scan')
    = render 'helpers/index_actions', record: record

app/views/scan_jobs/_show_tabs.html.slim
=  tabs active_tab, :main_info, from_external_link do |tabs|
  - tabs.add(:main_info, polymorphic_path(record, active_tab: :main_info)) do
    = fa_icon 'info'
    =< t('navigations.main_info')
  - tabs.add(:hosts, scan_jobs_hosts_path(job_id: record.id), 'ScanJobsHost', true) do
    = fa_icon 'sitemap'
    =< Host.model_name.human(count: 2)
  - tabs.add(:schedule, schedule_path(job_id: record.id, job_type: 'ScanJob'), 'Schedule', true) do
    = fa_icon 'clock-o'
    =< Schedule.model_name.human(count: 1)
  - tabs.add(:logs, scan_job_logs_path(job_id: record.id), 'ScanJobLog', true) do
    = fa_icon 'history'
    =< ScanJobLog.model_name.human(count: 2)
  - tabs.add(:links, polymorphic_path(record, active_tab: :links), 'Link') do
    = fa_icon 'link'
    =< Link.model_name.human(count: 2)
  - tabs.add(:tags, polymorphic_path(record, active_tab: :tags), 'Tag') do
    = fa_icon 'tags'
    =< Tag.model_name.human(count: 2)
  - tabs.add(:files, polymorphic_path(record, active_tab: :files), 'Attachment') do
    = fa_icon 'folder'
    =< AttachedFile.model_name.human(count: 2)

app/views/scan_jobs/index.html.slim
= caption @organization
= render 'organizations/show_tabs', record: @organization, active_tab: :scan_jobs, from_external_link: true
= index_new_button @records, organization_id: @organization.id
= render 'records', records: @records
= render 'index_paginate', records: @records