config/routes.rb
Rails.application.routes.draw do
  root to: 'organizations#index'

  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/no_roles', to: 'user_sessions#no_roles', as: :no_roles

  resources :organizations do
    get :autocomplete_organization_name, :on => :collection, as: :autocomplete
  end

  resources :users do
    get :autocomplete_user_name, :on => :collection, as: :autocomplete
    member do
      get 'change_password'
      patch 'update_password'
      patch 'generate_api_token'
    end
  end

  post '/departments/select', to: 'departments#select', as: :departments_select
  put '/departments/paste', to: 'departments#paste', as: :departments_paste
  get '/departments/reset', to: 'departments#reset', as: :departments_reset

  resources :roles do
    get :autocomplete_role_name, :on => :collection, as: :autocomplete
  end

  resources :role_members
  patch(
    '/role_members',
    to: 'role_members#clone',
    as: :clone_roles
  )

  resources :rights
  resources :departments do
    get :autocomplete_department_id, :on => :collection, as: :autocomplete
  end
  resources :agreements do
    get :autocomplete_agreement_prop, :on => :collection, as: :autocomplete
  end

  post '/uploads', to: 'attached_files#create', as: :uploads # For upload images via CKEditor
  resources :attached_files, only: [:create, :show, :destroy] # For attach/download/delete files in record by user
  # Show image in article
  get(
    'articles/:id/files/:file_name',
    to: 'attached_files#download_image',
    as: :article_download_file,
    constraints: { file_name: /[^\/]*/ }
  )

  resources :versions, only: [:index]
  resources :agreement_kinds
  resources :organization_kinds
  post "versions/:id/revert" => "versions#revert", as: :revert_version
  get "/attachments/:id/download", to: "attachments#download", as: :attachment_download
  resources :tag_kinds
  resources :tags
  resources :tag_members, only: %i[create destroy]
  resources :incidents do
    get :autocomplete_inciden_name, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'incidents#search', via: [:get, :post], as: :search
    end
  end
  resources :link_kinds
  resources :links, only: %i[create destroy]
  resources :record_templates
  get "/reports/:name", to: 'reports#show', as: :reports
  post "/reports/:name", to: 'reports#show', as: :filtred_reports
  get "/commands/:name", to: 'commands#run', as: :commands
  #mount Blazer::Engine, at: "blazer"
  get "/dashboards/", to: 'dashboards#index', as: :dashboards
  get "/investigations_dashboard/", to: 'dashboards#investigations_dashboard', as: :investigations_dashboard
  get "/vulnerabilities_dashboard/", to: 'dashboards#vulnerabilities_dashboard', as: :vulnerabilities_dashboard
  get "/user_actions_dashboard/", to: 'dashboards#user_actions_dashboard', as: :user_actions_dashboard
  get "/dashboards/:name", to: 'dashboards#show', as: :dashboard
  get "/charts/:name", to: 'charts#show', as: :charts
  resources :hosts do
    get :autocomplete_host_name, :on => :collection, as: :autocomplete
    member do
      patch :toggle_readable
    end
    collection do
      match 'search' => 'hosts#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
  end

  resources :articles do
    get :autocomplete_article_name, :on => :collection, as: :autocomplete
    collection do
      patch :toggle_subscription
    end
    member do
      patch :publicate
    end
  end

  resources :articles_folders
  post(
    '/articles_folders_select',
    to: 'articles_folders#select',
    as: :articles_folders_select
  )
  put(
    '/articles_folders_paste',
    to: 'articles_folders#paste',
    as: :articles_folders_paste
  )
  get(
    '/articles_folders_reset',
    to: 'articles_folders#reset',
    as: :articles_folders_reset
  )

  get '/serach/index', to: 'search#index', as: :search
  resources :scan_options
  resources :scan_jobs do
    member do
      get 'run'
    end
  end
  resources :scan_results, only: [:index, :show, :search] do
    collection do
      get 'open_ports'
      get 'new_ports'
      match 'search' => 'scan_results#search', via: [:post, :get], as: :search
    end
  end
  resources :host_service_statuses
  resources :host_services
  get '/schedule/', to: 'schedules#show', as: :schedule
  get '/schedules/', to: 'schedules#index', as: :schedules
  post '/schedule/', to: 'schedules#update', as: :update_schedule
  get '/scheduled_jobs/', to: 'scheduled_jobs#index', as: :scheduled_jobs
  delete '/scheduled_jobs/', to: 'scheduled_jobs#destroy', as: :destroy_scheduled_jobs
  resources :scan_jobs_hosts, only: [:index, :create, :destroy]
  resources :scan_job_logs, only: [:index]
  resources :feeds
  resources :investigation_kinds
  resources :investigations do
    collection do
      match 'search' => 'investigations#search', via: [:get, :post], as: :search
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
      post :clone
    end
  end
  resources :indicators do
    collection do
      match 'search' => 'indicators#search', via: [:get, :post], as: :search
      get :tree_show
      post :select
      put :paste
      get :reset
    end
    member do
      patch :toggle_readable
      patch :toggle_purpose
      patch :toggle_trust_level
    end
  end
  resources :enrichments, only: [:index, :show, :create, :destroy]
  resources :indicator_contexts
  resources :vulnerabilities do
    get :autocomplete_vulnerability_codename, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'vulnerabilities#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
    member do
      patch :toggle_processed
      patch :toggle_custom_relevance
      patch :toggle_readable
    end
  end
  resources :custom_fields
  resources :delivery_lists
  resources :delivery_subjects, only: [:index, :create, :destroy] do
    collection do
      get 'list_subjects'
      post 'notify' => 'delivery_subjects#notify', via: [:get], as: :notify
    end
    member do
      patch :toggle_readable
    end
  end
  resources :delivery_recipients, only: [:index, :create, :destroy]
  resources :search_filters
  resources :vulnerability_kinds
  resources :vulnerability_bulletin_kinds
  resources :vulnerability_bulletins do
    collection do
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
    end
  end
  resources :vulnerability_bulletin_members, only: %i[index create destroy]
  resources :vulnerability_bulletin_statuses

  resources :user_actions, only: [:index, :show]

  post '/translatet', to: 'translate#show', as: :translate

  resources :notifications_logs, only: [:index]

  resources :selectors, only: [:index]

  patch(
    '/selectors',
    to: 'selectors#update',
    as: :toggle_selection
  )
  delete(
    '/reset_selections',
    to: 'selectors#destroy',
    as: :reset_selections
  )

  patch(
    '/toggle_processed_processing_logs',
    to: 'processing_logs#toggle_processed',
    as: :toggle_processed_processing_logs
  )

  resources :custom_reports
  resources :custom_reports_folders do
    collection do
      post :paste
    end
  end

  resources :custom_reports_results, only: [:index, :show, :new, :create, :destroy, :download] do
    member do
      get 'download'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :custom_reports_api, only: [:show]
      resources :ra_api, only: [:create]
    end
  end

  resources :agents

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminSidekiqWebConstraint.new
  require 'sidekiq/cron/web'

  # TODO: use or delete (it for routing error handling when api client used)
  # match '*path', to: "api/v1/routing_error#show", format: true, constraints: {format: :json}, defaults: {format: 'html'}, via: [:get, :post]
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  include OrganizationAssociated
  include Schedule::Ransackers

  validates :job_id, uniqueness: { scope: :job_type }
  validates :job_id, presence: true
  validates :job_type, presence: true

  validate :check_minutes
  validate :check_hours
  validate :check_week_days
  validate :check_months
  validate :check_month_days

  belongs_to :job, polymorphic: true
  belongs_to :scan_job, class_name: 'ScanJob', foreign_key: :job_id, optional: true
  belongs_to :custom_report, class_name: 'CustomReport', foreign_key: :job_id, optional: true

  delegate :organization, to: :job, allow_nil: true, prefix: true

  after_save :update_sidekiq_cron_schedule

  after_destroy :destroy_sidekiq_cron_schedule

  def organization_id
    job.organization_id
  end

  def show_crontab_line
    return crontab_line if crontab_line.present?
    # TODO: think and if you wants do it with postgres function
    result = []
    %i[minutes hours month_days months week_days].each do |arr|
      result << array_to_crontab_symbol(self.send(arr))
    end
    return nil if result.all? { |value| value == '*' }
    result.join(' ')
  end

  def destroy_sidekiq_cron_schedule
    cron_job_name = "#{job_type}_#{job_id}"
    cron_job = Sidekiq::Cron::Job.find(cron_job_name)
    return unless cron_job
    cron_job.destroy
  end

  private

  def update_sidekiq_cron_schedule
    # if show_crontab_line = nil (m,h,md,m,wd = * * * * * and crontab_line is empty)
    unless show_crontab_line
      destroy_sidekiq_cron_schedule
      return
    end
    cron_job_name = "#{job_type}_#{job_id}"
    Sidekiq::Cron::Job.create(
      name: cron_job_name,
      cron: show_crontab_line,
      class: job.worker,
      queue: job.job_queue,
      args: [job.id, job.job_queue]
    )
  end

  def array_to_crontab_symbol(arr)
    arr.present? ? arr.sort.join(',') : '*'
  end

  def check_minutes
    return if check_array(minutes, 0..59)
    errors.add(:minutes, :invalid)
  end

  def check_hours
    return if check_array(hours, 0..23)
    errors.add(:hours, :invalid)
  end

  def check_week_days
    return if check_array(week_days, 0..6)
    errors.add(:week_days, :invalid)
  end

  def check_months
    return if check_array(months, 1..12)
    errors.add(:months, :invalid)
  end

  def check_month_days
    return if check_array(month_days, 1..31)
    errors.add(:month_days, :invalid)
  end

  def check_array(array, range)
    array.is_a?(Array) && array.all?{|value| (range).include?(value)}
  end
end

app/models/schedule/ransackers.rb
# frozen_string_literal: true

module Schedule::Ransackers
  extend ActiveSupport::Concern

  included do
    ransacker :sharp_id do
      Arel.sql("'#' || schedules.id::text")
    end
    # TODO: User or delete
#    ransacker :month_str do
#      field_transformation = <<~SQL
#        CASE schedules.month
#        WHEN 0
#        THEN '#{states[0]}'
#        WHEN 1
#        THEN '#{states[1]}'
#        WHEN 2
#        THEN '#{states[2]}'
#        END
#      SQL
#      Arel.sql(field_transformation)
#    end
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  include Record

  def show
    @job = params[:job_type].constantize.find(params[:job_id])
    @record = model.where(job_id: params[:job_id])
                   .where(job_type: params[:job_type])
                   .first_or_initialize

    authorize @record
    @partial = case params[:job_type]
               when 'ScanJob'
                 'scan_jobs/show_tabs'
               when 'CustomReport'
                 'custom_reports/show_tabs'
               end
  end

  def update
    @job = params[:job_type].constantize.find(params[:job_id])
    @record = model.where(job_id: params[:job_id])
                   .where(job_type: params[:job_type])
                   .first_or_initialize
    authorize @record
    @record.current_user = current_user
    @record.job_id = @job.id
    @record.job_type = @job.class
    update_minutes if params[:minute]
    update_hours if params[:hour]
    update_week_days if params[:week_day]
    update_month_days if params[:month_day]
    update_months if params[:month]
    update_crontab_line if params[:crontab_line]
    # TODO: add errors show for handling in Schedule.save and Sidekiq::Cron.save
    @record.save!
  rescue ActiveRecord::RecordInvalid
    logger = ActiveSupport::TaggedLogging.new(Logger.new("log/rism_erros.log"))
    logger.tagged("SCHEDULE: #{@record&.job&.name}") do
      logger.error("schedule can`t be saved - #{@record.errors.full_messages}")
    end
  end

  private

  def update_crontab_line
    @record.crontab_line = params[:crontab_line]
    render 'renew_crontab_line'
  end

  def update_minutes
    if params[:destroy]
      @record.minutes = @record.minutes - [params[:minute].to_i]
    else
      @record.minutes = @record.minutes | [params[:minute]]
    end
    render 'renew_minutes'
  end

  def update_hours
    if params[:destroy]
      @record.hours = @record.hours - [params[:hour].to_i]
    else
      @record.hours = @record.hours | [params[:hour]]
    end
    render 'renew_hours'
  end

  def update_week_days
    if params[:destroy]
      @record.week_days = @record.week_days - [params[:week_day].to_i]
    else
      @record.week_days = @record.week_days | [params[:week_day]]
    end
    render 'renew_week_days'
  end

  def update_month_days
    if params[:destroy]
      @record.month_days = @record.month_days - [params[:month_day].to_i]
    else
      @record.month_days = @record.month_days | [params[:month_day]]
    end
    render 'renew_month_days'
  end

  def update_months
    if params[:destroy]
      @record.months = @record.months - [params[:month].to_i]
    else
      @record.months = @record.months | [params[:month]]
    end
    render 'renew_month'
  end

  def model
    Schedule
  end

  def default_sort
    'created_at desc'
  end
end

app/views/schedules/_caption.html.slim
#caption
  h3
    span.text-info
      = "#{t 'labels.schedules.current_schedule'}: "
    a href="#" data-toggle="tooltip" title= t('placeholders.schedules.crontab_line')
      span.text-warning
        = @record.show_crontab_line || ''

app/views/schedules/_crontab_line_form.html.slim
#crontab_line
  = form_for @record, url: update_schedule_path, method: :post, remote: true, html: {class: 'form-horizontal'} do |f|

    = label_tag :organization_id, class: 'control-label' do
      a.link data-toggle='collapse' data-turbolinks='false' href='#expert_mode'
        strong.text-info
          = t('labels.expert_mode')

    .collapse#expert_mode
      = hidden_field_tag :job_id, @record.job_id
      = hidden_field_tag :job_type, @record.job_type
      = label_tag :crontab_line, Schedule.human_attribute_name(:crontab_line), class: 'control-label'
      =< text_field_tag :crontab_line, @record.crontab_line, class: 'form-control', style: 'width:60%; display:inline', placeholder: t('placeholders.schedules.crontab_line')
      =< submit_tag t('helpers.submit.save'), class: 'btn btn-success'
  br

app/views/schedules/_hours.html.slim
#hours
  table.table.table-bordered.table-condensed
    caption
      strong.text-info
        = Schedule.human_attribute_name(:hours)
        =< fa_icon 'clock-o'
    tbody
      - (0..23).step(12) do |big_step|
        tr
         - (0..11).each do |smal_step|
           - hour = big_step + smal_step
           - if @record.hours.include?(hour)
             td.success
               = link_to schedule_path(job_id: @job.id, job_type: @job.class, hour: hour, destroy: true), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
                 = hour
           - else
             td.warning
               = link_to schedule_path(job_id: @job.id, job_type: @job.class, hour: hour), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.add')  do
                 = hour

app/views/schedules/_minutes.html.slim
#minutes
  table.table.table-bordered.table-condensed
    caption
      strong.text-info
        = Schedule.human_attribute_name(:minutes)
        =< fa_icon 'clock-o'
    tbody
      - (0..40).step(20) do |big_step|
        tr
         - (0..19).each do |small_step|
           - minute = big_step + small_step
           - if @record.minutes.include?(minute)
             td.success
               = link_to schedule_path(job_id: @job.id, job_type: @job.class, minute: minute, destroy: true), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
                 = minute
           - else
             td.warning
               = link_to schedule_path(job_id: @job.id, job_type: @job.class, minute: minute ), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.add')  do
                 = minute

app/views/schedules/_month_days.html.slim
#month_days
  table.table.table-bordered.table-condensed
    caption
      strong.text-info
        = Schedule.human_attribute_name(:month_days)
        =< fa_icon 'calendar'
    tbody
      - (1..31).step(7) do |big_step|
        tr
         - (0..6).each do |smal_step|
           - month_day = big_step + smal_step
           - break if month_day > 31
           - if @record.month_days.include?(month_day)
             td.success
               = link_to schedule_path(job_id: @job.id, job_type: @job.class, month_day: month_day, destroy: true), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
                 = month_day
           - else
             td.warning
               = link_to schedule_path(job_id: @job.id, job_type: @job.class, month_day: month_day), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.add')  do
                  = month_day

app/views/schedules/_months.html.slim
#months
  table.table.table-bordered.table-condensed
    caption
      strong.text-info
        = Schedule.human_attribute_name(:months)
        =< fa_icon 'calendar'
    tbody
      tr
       - (1..12).each do |month|
         - if @record.months.include?(month)
           td.success
             = link_to schedule_path(job_id: @job.id, job_type: @job.class, month: month, destroy: true), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
               = t('date.month_names2')[month]
         - else
           td.warning
             = link_to schedule_path(job_id: @job.id, job_type: @job.class, month: month), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.add')  do
               = t('date.month_names2')[month]

app/views/schedules/_records.html.slim
= index_search :sharp_id_or_job_of_ScanJob_type_name_or_job_of_ScanJob_type_organization_name_cont
= command_button_for records
= index_for records, decorator: ScheduleDecorator, actions: false do |t|
  - t.header attribute: :id, sort_by: :id, sort: :desc
  - t.header attribute: :job_of_ScanJob_name, label: ScanJob.model_name.human
  - t.header attribute: :job_organization
  - t.header attribute: :week_days
  - t.header attribute: :month_days
  - t.header attribute: :months
  - t.header attribute: :job, label:  t('labels.schedules.current_schedule')
  - t.field { |record| link_to record.id, schedule_path(job_type: 'ScanJob', job_id: record&.job&.id) }
  - t.field { |record| link_to record&.job&.name, record.job }
  - t.field { |record| link_to record&.job_organization&.name, record.job_organization }
  - t.field { |record| link_to record.show_week_days, schedule_path(job_type: 'ScanJob', job_id: record&.job&.id) }
  - t.field { |record| link_to record.show_month_days, schedule_path(job_type: 'ScanJob', job_id: record&.job&.id) }
  - t.field { |record| link_to record.show_months, schedule_path(job_type: 'ScanJob', job_id: record&.job&.id) }
  - t.field do |record|
    = link_to schedule_path(job_type: 'ScanJob', job_id: record&.job&.id)
      - if record.show_crontab_line.present?
        = record.show_crontab_line

app/views/schedules/_week_days.html.slim
#week_days
  table.table.table-bordered.table-condensed
    caption
      strong.text-info
        = Schedule.human_attribute_name(:week_days)
        =< fa_icon 'calendar'
    tbody
      tr
       - (0..6).each do |week_day|
         - if @record.week_days.include?(week_day)
           td.success
             = link_to schedule_path(job_id: @job.id, job_type: @job.class, week_day: week_day, destroy: true), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
               = t('date.day_names')[week_day]
         - else
           td.warning
             = link_to schedule_path(job_id: @job.id, job_type: @job.class, week_day: week_day), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.add')  do
               = t('date.day_names')[week_day]

app/views/schedules/index.html.slim
= caption @records
= render 'records', records: @records
= render 'index_paginate', records: @records

app/views/schedules/renew_crontab_line.js.erb
$("#crontab_line").html("<%= escape_javascript(render partial: 'crontab_line_form') %>");
$("#caption").html("<%= escape_javascript(render partial: 'caption') %>");

app/views/schedules/renew_minutes.js.erb
$("#minutes").html("<%= escape_javascript(render partial: 'minutes') %>");
$("#caption").html("<%= escape_javascript(render partial: 'caption') %>");

app/views/schedules/renew_month.js.erb
$("#months").html("<%= escape_javascript(render partial: 'months') %>");
$("#caption").html("<%= escape_javascript(render partial: 'caption') %>");

app/views/schedules/renew_month_days.js.erb
$("#month_days").html("<%= escape_javascript(render partial: 'month_days') %>");
$("#caption").html("<%= escape_javascript(render partial: 'caption') %>");

app/views/schedules/show.html.slim
= caption @job
= render @partial, record: @job, active_tab: :schedule, from_external_link: true
= render 'record', record: @record