config/routes.rb
Rails.application.routes.draw do
  root to: 'organizations#index'

  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/no_roles', to: 'user_sessions#no_roles', as: :no_roles

  resources :organizations do
    get :autocomplete_organization_name, :on => :collection, as: :autocomplete
  end

  resources :users do
    get :autocomplete_user_name, :on => :collection, as: :autocomplete
    member do
      get 'change_password'
      patch 'update_password'
      patch 'generate_api_token'
    end
  end

  post '/departments/select', to: 'departments#select', as: :departments_select
  put '/departments/paste', to: 'departments#paste', as: :departments_paste
  get '/departments/reset', to: 'departments#reset', as: :departments_reset

  resources :roles do
    get :autocomplete_role_name, :on => :collection, as: :autocomplete
  end

  resources :role_members
  patch(
    '/role_members',
    to: 'role_members#clone',
    as: :clone_roles
  )

  resources :rights
  resources :departments do
    get :autocomplete_department_id, :on => :collection, as: :autocomplete
  end
  resources :agreements do
    get :autocomplete_agreement_prop, :on => :collection, as: :autocomplete
  end

  post '/uploads', to: 'attached_files#create', as: :uploads # For upload images via CKEditor
  resources :attached_files, only: [:create, :show, :destroy] # For attach/download/delete files in record by user
  # Show image in article
  get(
    'articles/:id/files/:file_name',
    to: 'attached_files#download_image',
    as: :article_download_file,
    constraints: { file_name: /[^\/]*/ }
  )

  resources :versions, only: [:index]
  resources :agreement_kinds
  resources :organization_kinds
  post "versions/:id/revert" => "versions#revert", as: :revert_version
  get "/attachments/:id/download", to: "attachments#download", as: :attachment_download
  resources :tag_kinds
  resources :tags
  resources :tag_members, only: %i[create destroy]
  resources :incidents do
    get :autocomplete_inciden_name, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'incidents#search', via: [:get, :post], as: :search
    end
  end
  resources :link_kinds
  resources :links, only: %i[create destroy]
  resources :record_templates
  get "/reports/:name", to: 'reports#show', as: :reports
  post "/reports/:name", to: 'reports#show', as: :filtred_reports
  get "/commands/:name", to: 'commands#run', as: :commands
  #mount Blazer::Engine, at: "blazer"
  get "/dashboards/", to: 'dashboards#index', as: :dashboards
  get "/investigations_dashboard/", to: 'dashboards#investigations_dashboard', as: :investigations_dashboard
  get "/vulnerabilities_dashboard/", to: 'dashboards#vulnerabilities_dashboard', as: :vulnerabilities_dashboard
  get "/user_actions_dashboard/", to: 'dashboards#user_actions_dashboard', as: :user_actions_dashboard
  get "/dashboards/:name", to: 'dashboards#show', as: :dashboard
  get "/charts/:name", to: 'charts#show', as: :charts
  resources :hosts do
    get :autocomplete_host_name, :on => :collection, as: :autocomplete
    member do
      patch :toggle_readable
    end
    collection do
      match 'search' => 'hosts#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
  end

  resources :articles do
    get :autocomplete_article_name, :on => :collection, as: :autocomplete
    collection do
      patch :toggle_subscription
    end
    member do
      patch :publicate
    end
  end

  resources :articles_folders
  post(
    '/articles_folders_select',
    to: 'articles_folders#select',
    as: :articles_folders_select
  )
  put(
    '/articles_folders_paste',
    to: 'articles_folders#paste',
    as: :articles_folders_paste
  )
  get(
    '/articles_folders_reset',
    to: 'articles_folders#reset',
    as: :articles_folders_reset
  )

  get '/serach/index', to: 'search#index', as: :search
  resources :scan_options
  resources :scan_jobs do
    member do
      get 'run'
    end
  end
  resources :scan_results, only: [:index, :show, :search] do
    collection do
      get 'open_ports'
      get 'new_ports'
      match 'search' => 'scan_results#search', via: [:post, :get], as: :search
    end
  end
  resources :host_service_statuses
  resources :host_services
  get '/schedule/', to: 'schedules#show', as: :schedule
  get '/schedules/', to: 'schedules#index', as: :schedules
  post '/schedule/', to: 'schedules#update', as: :update_schedule
  get '/scheduled_jobs/', to: 'scheduled_jobs#index', as: :scheduled_jobs
  delete '/scheduled_jobs/', to: 'scheduled_jobs#destroy', as: :destroy_scheduled_jobs
  resources :scan_jobs_hosts, only: [:index, :create, :destroy]
  resources :scan_job_logs, only: [:index]
  resources :feeds
  resources :investigation_kinds
  resources :investigations do
    collection do
      match 'search' => 'investigations#search', via: [:get, :post], as: :search
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
      post :clone
    end
  end
  resources :indicators do
    collection do
      match 'search' => 'indicators#search', via: [:get, :post], as: :search
      get :tree_show
      post :select
      put :paste
      get :reset
    end
    member do
      patch :toggle_readable
      patch :toggle_purpose
      patch :toggle_trust_level
    end
  end
  resources :enrichments, only: [:index, :show, :create, :destroy]
  resources :indicator_contexts
  resources :vulnerabilities do
    get :autocomplete_vulnerability_codename, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'vulnerabilities#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
    member do
      patch :toggle_processed
      patch :toggle_custom_relevance
      patch :toggle_readable
    end
  end
  resources :custom_fields
  resources :delivery_lists
  resources :delivery_subjects, only: [:index, :create, :destroy] do
    collection do
      get 'list_subjects'
      post 'notify' => 'delivery_subjects#notify', via: [:get], as: :notify
    end
    member do
      patch :toggle_readable
    end
  end
  resources :delivery_recipients, only: [:index, :create, :destroy]
  resources :search_filters
  resources :vulnerability_kinds
  resources :vulnerability_bulletin_kinds
  resources :vulnerability_bulletins do
    collection do
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
    end
  end
  resources :vulnerability_bulletin_members, only: %i[index create destroy]
  resources :vulnerability_bulletin_statuses

  resources :user_actions, only: [:index, :show]

  post '/translatet', to: 'translate#show', as: :translate

  resources :notifications_logs, only: [:index]

  resources :selectors, only: [:index]

  patch(
    '/selectors',
    to: 'selectors#update',
    as: :toggle_selection
  )
  delete(
    '/reset_selections',
    to: 'selectors#destroy',
    as: :reset_selections
  )

  patch(
    '/toggle_processed_processing_logs',
    to: 'processing_logs#toggle_processed',
    as: :toggle_processed_processing_logs
  )

  resources :custom_reports
  resources :custom_reports_folders do
    collection do
      post :paste
    end
  end

  resources :custom_reports_results, only: [:index, :show, :new, :create, :destroy, :download] do
    member do
      get 'download'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :custom_reports_api, only: [:show]
      resources :ra_api, only: [:create]
    end
  end

  resources :agents

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminSidekiqWebConstraint.new
  require 'sidekiq/cron/web'

  # TODO: use or delete (it for routing error handling when api client used)
  # match '*path', to: "api/v1/routing_error#show", format: true, constraints: {format: :json}, defaults: {format: 'html'}, via: [:get, :post]
end

app/helpers/advanced_search_helper.rb
# frozen_string_literal: true

module AdvancedSearchHelper
  def setup_search_form(builder)
    fields = builder.grouping_fields builder.object.new_grouping,
      object_name: 'new_object_name', child_index: 'new_grouping' do |f|
      render('grouping_fields', f: f)
    end
    content_for :document_ready, %Q{
      var search = new Search({grouping: "#{escape_javascript(fields)}"});
      $(document).on("click", "button.add_fields", function() {
        search.add_fields(this, $(this).data('fieldType'), $(this).data('content'));
        return false;
      });
      $(document).on("click", "button.remove_fields", function() {
        search.remove_fields(this);
        return false;
      });
      $(document).on("click", "button.nest_fields", function() {
        search.nest_fields(this, $(this).data('fieldType'));
        return false;
      });
    }.html_safe
  end

  def button_to_remove_fields
    tag.button 'Remove', class: 'remove_fields btn btn-danger', type: 'button'
  end

  def button_to_add_fields(f, type)
    new_object = f.object.send("build_#{type}")
    name = "#{type}_fields"
    fields = f.send(name, new_object, child_index: "new_#{type}") do |builder|
      render(name, f: builder)
    end

    tag.button button_label[type], class: 'add_fields btn btn-info', 'data-field-type': type,
      'data-content': "#{fields}"
  end

  def button_to_nest_fields(type)
    tag.button button_label[type], class: 'nest_fields btn btn-info', 'data-field-type': type
  end

  def button_label
    { value:     'Add Value',
      condition: 'Add Condition',
      sort:      'Add Sort',
      grouping:  'Add Condition Group' }.freeze
  end

  #TODO: user or delete
  def action
    if action_name == 'advanced_search'
      :post
    else
      :get
    end
  end

  #TODO: user or delete
  def link_to_toggle_search_modes
    if action_name == 'advanced_search'
      link_to('Go to Simple mode', users_path)
    else
      link_to('Go to Advanced mode', advanced_search_users_path)
    end
  end

  #TODO: user or delete
  def user_column_headers
    %i(id first_name last_name email created_at updated_at).freeze
  end

  #TODO: user or delete
  def user_column_fields
    %i(id first_name last_name email created updated).freeze
  end

  #TODO: user or delete
  def results_limit
    # max number of search results to display
    10
  end

  #TODO: user or delete
  def post_title_length
    # max number of characters in posts titles to display
    14
  end

  #TODO: user or delete
  def post_title_header_labels
    %w(1 2 3).freeze
  end

  #TODO: user or delete
  def user_posts_and_comments
    %w(posts comments).freeze
  end

  #TODO: user or delete
  def condition_fields
    %w(fields condition).freeze
  end

  #TODO: user or delete
  def value_fields
    %w(fields value).freeze
  end

  #TODO: user or delete
  def display_distinct_label_and_check_box
    tag.section do
      check_box_tag(:distinct, '1', user_wants_distinct_results?, class: :cbx) +
      label_tag(:distinct, 'Return distinct records')
    end
  end

  #TODO: user or delete
  def user_wants_distinct_results?
    params[:distinct].to_i == 1
  end

  #TODO: user or delete
  def display_query_sql(users)
    tag.p('SQL:') + tag.code(users.to_sql)
  end

  #TODO: user or delete
  def display_results_header(count)
    if count > results_limit
      "Your first #{results_limit} results out of #{count} total"
    else
      "Your #{pluralize(count, 'result')}"
    end
  end

  #TODO: user or delete
  def display_sort_column_headers(search)
    user_column_headers.reduce(String.new) do |string, field|
      string << (tag.th sort_link(search, field, {}, method: action))
    end +
    post_title_header_labels.reduce(String.new) do |str, i|
      str << (tag.th "Post #{i} title")
    end
  end

  #TODO: user or delete
  def display_search_results(objects)
    objects.limit(results_limit).reduce(String.new) do |string, object|
      string << (tag.tr display_search_results_row(object))
    end
  end

  #TODO: user or delete
  def display_search_results_row(object)
    user_column_fields.reduce(String.new) do |string, field|
      string << (tag.td object.send(field))
    end
    .html_safe +
    display_user_posts(object.posts)
  end

  #TODO: user or delete
  def display_user_posts(posts)
    posts.reduce(String.new) do |string, post|
      string << (tag.td truncate(post.title, length: post_title_length))
    end
    .html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caption_helper.rb
# frozen_string_literal: true

# = Page caption helper
# Convert object to text,
# that can be used as show or index page caption
# (title over a table with records or record attributes).
#
# It assumes that bootstrap and slim is used in the Rails project.
module CaptionHelper
  CAPTION_TAG = 'h3'
  CAPTION_CLASS = 'caption text-info'

  # Generate page caption
  #
  # ==== Attributes
  # Method can take three first argument types:
  # * +record+   - one record (model instance)
  # * +records+  - several records (ActiveRelation instance)
  # * +text+   - text string
  #
  # ==== Options
  # You can customize output (set HTML tag, class, id) by
  # set options hash as second argument.
  #
  # * +:tag+   - Specifies html tag (default is <h3>)
  # * +:id+    - Specifies html id
  # * +:class+  - Specifies html class (default is text-info)
  #
  # ==== Examples
  #  caption(@user)        # => <h3 class='text-primary'>User</h3>
  #
  #  caption(@users)       # => <h3 class='text-primary'>Users</h3>
  #
  #  caption('Text')       # => <h3 class='text-primary'>Text</h3>
  #
  #  caption(@record, tag: :span, class: 'text-primary', id: 'caption1')
  #  # => <span class='text-primary' id='caption1'> Record </span>
  def caption(record_or_records_or_text, options = {})
    options.slice(:tag, :class, :id)
    options[:tag] ||= CAPTION_TAG
    options[:class] ||= CAPTION_CLASS
    caption = case record_or_records_or_text
              when ActiveRecord::Relation
                record_or_records_or_text.klass
                                         .model_name
                                         .human(count: 2)
              when ActiveRecord::Base
                result = record_or_records_or_text.class
                                                  .model_name
                                                  .human
                if record_or_records_or_text.respond_to?(:name)
                  result += ": #{record_or_records_or_text.name}"
                end
                result
              when String
                record_or_records_or_text
              else
                raise(
                  ArgumentError,
                  'It should be a one record, several records or text string.'
                )
              end
    render('helpers/caption', caption: caption,
                              tag: options)
  end
end

app/helpers/chart_helper.rb
# frozen_string_literal: true

module ChartHelper
  def chart(name, options = {})
    chart = Charts.chart_by_name(name)
    render(
      'helpers/chart',
      chart: chart,
      options: options
    )
  end
end

app/helpers/color_icon_helper.rb
# frozen_string_literal: true

module ColorIconHelper
  def color_icon(color, icon = 'star')
    render(
      'helpers/color_icon',
      color: color,
      icon: icon
    )
  end
end

app/helpers/command_button_helper.rb
# frozen_string_literal: true

# = Commnad button helper
# Make links to allowed for record or records commands
#
# It assumes that bootstrap and slim is used in the Rails project.
module CommandButtonHelper
  def command_button_for(record_or_records, options = {})
    options = options.select { |key, value| value }
    command_model = case record_or_records
              when ActiveRecord::Relation
                record_or_records.klass
                                 .model_name
              when ActiveRecord::Base
                record_or_records.class
                                 .model_name
              else
                raise(
                  ArgumentError,
                  'It should be a one record or several records.'
                )
              end
    commands = Commands.names_where(
      command_model: command_model,
      params: options
    )
    return if commands.blank?
    render(
      'helpers/command_button',
      commands: commands,
      options: options
    )
  end
end

app/helpers/custom_fields_input_helper.rb
# frozen_string_literal: true

module CustomFieldsInputHelper
  def custom_fields_input(record)
    fields = record.class.custom_fields_list
    render(
      'helpers/custom_fields_input',
      fields: fields,
      record: record,
      resource: record.class.model_name.to_s.underscore,
    )
  end
end

app/helpers/date_time_helper.rb
# frozen_string_literal: true

module DateTimeHelper
  def show_date(field)
    return '' if field.blank?
    field.strftime('%d.%m.%Y')
  end

  def show_date_time(field)
    return '' if field.blank?
    field.strftime('%d.%m.%Y-%H:%M')
  end

  def time_value(record, field)
    return record.send(field) if record.send(field) && record
    nil
  end

  def start_year
    Date.current.year
  end

  def end_year
    15.years.ago.year
  end

end

app/helpers/index_search_helper.rb
# frozen_string_literal: true

module IndexSearchHelper
  def index_search(search_fields, options = {})
    options[:placeholder] ||= t('placeholders.search')
    options[:size] ||= 50
    options[:html_method] ||= :get
    render 'helpers/index_search', search_fields: search_fields,
                                   options: options
  end
end

app/views/helpers/_chart.html.slim
h3
  = chart.human_name
.chart
  = send(chart.kind,
    charts_path(name: chart.chart_name))

app/views/helpers/_color_icon.html.slim
span style="color:#{color}"
  => fa_icon icon

app/views/helpers/_command_button.html.slim
- if current_user.admin?
  .pull-right
    .btn-group
      button.btn.btn-default.dropdown-toggle data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
        i.text-info
          = fa_icon 'gear'
        =<> t('navigations.commands.run')
        span.caret
      ul.dropdown-menu.dropdown-menu-right
        - commands.each do |command|
          li
            = link_to commands_path({name: command.command_name}.merge(options)), data: {turbolinks: false, confirm: t('views.action.confirm')} do
              span.text-info
                = fa_icon 'gear'
              =< command.human_name

app/views/helpers/_custom_fields_input.html.slim
- fields.each do |cf|
  .form-group
    .field
      .col-lg-2.text-right
        = label_tag "#{resource}[custom_fields][#{cf.name}]", cf.name, class: 'control-label'
      .col-lg-8
        - if cf.data_type == 'text'
          = text_area_tag "#{resource}[custom_fields][#{cf.name}]", record.custom_field(cf.name), class: 'form-control', rows: 8
        - else
          = text_field_tag "#{resource}[custom_fields][#{cf.name}]", record.custom_field(cf.name), class: 'form-control'

app/views/helpers/_index.html.slim
table.table.table-hover.table-bordered.table-striped
  thead.thead-dark
    tr
      - headers.each do |header|
        th
          - if header[:sort]
            - if header[:sort_array]
              = sort_link @q, header[:sort_by], header[:sort_array], default_order: header[:sort] do
                span.text-info
                  = header[:label]
            - else
              = sort_link @q, header[:sort_by], default_order: header[:sort] do
                span.text-info
                  = header[:label]
          - else
            span.text-info
              = header[:label]
      - if options[:actions]
        th.fit
  tbody
    - if top_rows.present?
      - top_rows.each do |top_row|
        = top_row
    - records.each do |record|
      tr
        - field_handlers.each_with_index do |handler, i|
          - if headers[i].fetch(:fit, false)
            td.fit
              - field = capture { handler.call(record) }
              = field
          - else
            td
              - field = capture { handler.call(record) }
              = field
        - if options[:actions]
          td.fit
            = render 'helpers/index_actions', record: record

app/views/helpers/_index_actions.html.slim
=> link_to polymorphic_path(record), class: 'btn btn-link btn-xs' do
  = fa_icon 'eye', class: 'text-info', data_toggle: 'tooltip', title: t('views.action.show')
- if current_user.admin_editor? || current_user.can?(:edit, @records.klass)
  => link_to edit_polymorphic_path(record), class: 'btn btn-link btn-xs' do
    = fa_icon 'pencil', class: 'text-warning', data_toggle: 'tooltip', title: t('views.action.edit')
  = link_to record, data: {confirm: t('views.action.confirm')}, method: :delete, class: 'btn btn-link btn-xs' do
    = fa_icon 'remove', class: 'text-danger', data_toggle: 'tooltip', title: t('views.action.delete')

app/views/helpers/_index_new_button.html.slim
- if current_user.admin_editor? || current_user.can?(:edit, model)
  .pull-right
    .btn-group
      = link_to new_polymorphic_path(model, options), class: 'btn btn-default' do
        i.text-success
          = fa_icon 'plus-circle'
        =< label
      = template_button model, current_user, options

app/views/helpers/_index_search.html.slim
= search_form_for @q, class: 'form-inline', url: options[:url], html: { method: options[:html_method] } do |f|
  - options.each do |k, v|
    = f.hidden_field k, value: v
  .form-group.pull-left
    .input-group
      = f.search_field(search_fields,
        placeholder: options[:placeholder],
        size: options[:size],
        id: 'clearable',
        class: 'form-control')
      = tag.span(id: 'remove',
        onclick: "document.getElementById('clearable').value = ''",
        class: 'link')
        = fa_icon 'remove'
      .input-group-btn
        = button_tag class: 'btn btn-default' do
          span.glyphicon.glyphicon-search
          =< t('views.action.find')

app/views/helpers/_menu_li.html.slim
= tag.li class: options[:result_class], role: options[:role] do
  = content

app/views/helpers/_report_button.html.slim
.pull-right
  .btn-group
    button.btn.btn-default.dropdown-toggle data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
      i.text-info
        = fa_icon 'save'
      =<> t('navigations.reports.download')
      span.caret
    ul.dropdown-menu.dropdown-menu-right
      - reports.each do |report|
        li
          = report.human_name
          | :
          - report.formats.each do |f|
            =< link_to reports_path({name: report.report_name, format: f}.merge(options)), data: {turbolinks: false} do
              span.text-info
                = fa_icon 'save'
              span.text-warning
                =< f

app/views/helpers/_show_attribute.html.slim
tr
  td.col-md-2.text-right
    strong.text-info
      = attribute_label
  td
    = attribute_value

app/views/helpers/_show_record.html.slim
table.table.table-hover.table-bordered.table-striped
  = yield(record)

app/views/helpers/_tabs.html.slim
ul.nav.nav-tabs role='tablist'
  - tabs.each do |tab|
    li class=active_tab.fetch(tab[:name],'') role='presentation'
      - if from_external_page || tab[:external_link]
        = link_to(tab[:link]) do
          = capture { tab[:label].call }
      - else
        = link_to("##{tab[:name]}", {'aria-controls' => tab[:name], role: 'tab', data: {toggle: 'tab' }}) do
          = capture { tab[:label].call }
br

app/views/helpers/_tabs_panes.html.slim
.tab-content
  - panes.each do |pane|
    . role='tabpanel' id=pane[:name] class="tab-pane#{active_pane.fetch(pane[:name],'')}"
      = capture { pane[:content].call }