config/routes.rb
Rails.application.routes.draw do
  root to: 'organizations#index'

  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/no_roles', to: 'user_sessions#no_roles', as: :no_roles

  resources :organizations do
    get :autocomplete_organization_name, :on => :collection, as: :autocomplete
  end

  resources :users do
    get :autocomplete_user_name, :on => :collection, as: :autocomplete
    member do
      get 'change_password'
      patch 'update_password'
      patch 'generate_api_token'
    end
  end

  post '/departments/select', to: 'departments#select', as: :departments_select
  put '/departments/paste', to: 'departments#paste', as: :departments_paste
  get '/departments/reset', to: 'departments#reset', as: :departments_reset

  resources :roles do
    get :autocomplete_role_name, :on => :collection, as: :autocomplete
  end

  resources :role_members
  patch(
    '/role_members',
    to: 'role_members#clone',
    as: :clone_roles
  )

  resources :rights
  resources :departments do
    get :autocomplete_department_id, :on => :collection, as: :autocomplete
  end
  resources :agreements do
    get :autocomplete_agreement_prop, :on => :collection, as: :autocomplete
  end

  post '/uploads', to: 'attached_files#create', as: :uploads # For upload images via CKEditor
  resources :attached_files, only: [:create, :show, :destroy] # For attach/download/delete files in record by user
  # Show image in article
  get(
    'articles/:id/files/:file_name',
    to: 'attached_files#download_image',
    as: :article_download_file,
    constraints: { file_name: /[^\/]*/ }
  )

  resources :versions, only: [:index]
  resources :agreement_kinds
  resources :organization_kinds
  post "versions/:id/revert" => "versions#revert", as: :revert_version
  get "/attachments/:id/download", to: "attachments#download", as: :attachment_download
  resources :tag_kinds
  resources :tags
  resources :tag_members, only: %i[create destroy]
  resources :incidents do
    get :autocomplete_inciden_name, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'incidents#search', via: [:get, :post], as: :search
    end
  end
  resources :link_kinds
  resources :links, only: %i[create destroy]
  resources :record_templates
  get "/reports/:name", to: 'reports#show', as: :reports
  post "/reports/:name", to: 'reports#show', as: :filtred_reports
  get "/commands/:name", to: 'commands#run', as: :commands
  #mount Blazer::Engine, at: "blazer"
  get "/dashboards/", to: 'dashboards#index', as: :dashboards
  get "/investigations_dashboard/", to: 'dashboards#investigations_dashboard', as: :investigations_dashboard
  get "/vulnerabilities_dashboard/", to: 'dashboards#vulnerabilities_dashboard', as: :vulnerabilities_dashboard
  get "/user_actions_dashboard/", to: 'dashboards#user_actions_dashboard', as: :user_actions_dashboard
  get "/dashboards/:name", to: 'dashboards#show', as: :dashboard
  get "/charts/:name", to: 'charts#show', as: :charts
  resources :hosts do
    get :autocomplete_host_name, :on => :collection, as: :autocomplete
    member do
      patch :toggle_readable
    end
    collection do
      match 'search' => 'hosts#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
  end

  resources :articles do
    get :autocomplete_article_name, :on => :collection, as: :autocomplete
    collection do
      patch :toggle_subscription
    end
    member do
      patch :publicate
    end
  end

  resources :articles_folders
  post(
    '/articles_folders_select',
    to: 'articles_folders#select',
    as: :articles_folders_select
  )
  put(
    '/articles_folders_paste',
    to: 'articles_folders#paste',
    as: :articles_folders_paste
  )
  get(
    '/articles_folders_reset',
    to: 'articles_folders#reset',
    as: :articles_folders_reset
  )

  get '/serach/index', to: 'search#index', as: :search
  resources :scan_options
  resources :scan_jobs do
    member do
      get 'run'
    end
  end
  resources :scan_results, only: [:index, :show, :search] do
    collection do
      get 'open_ports'
      get 'new_ports'
      match 'search' => 'scan_results#search', via: [:post, :get], as: :search
    end
  end
  resources :host_service_statuses
  resources :host_services
  get '/schedule/', to: 'schedules#show', as: :schedule
  get '/schedules/', to: 'schedules#index', as: :schedules
  post '/schedule/', to: 'schedules#update', as: :update_schedule
  get '/scheduled_jobs/', to: 'scheduled_jobs#index', as: :scheduled_jobs
  delete '/scheduled_jobs/', to: 'scheduled_jobs#destroy', as: :destroy_scheduled_jobs
  resources :scan_jobs_hosts, only: [:index, :create, :destroy]
  resources :scan_job_logs, only: [:index]
  resources :feeds
  resources :investigation_kinds
  resources :investigations do
    collection do
      match 'search' => 'investigations#search', via: [:get, :post], as: :search
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
      post :clone
    end
  end
  resources :indicators do
    collection do
      match 'search' => 'indicators#search', via: [:get, :post], as: :search
      get :tree_show
      post :select
      put :paste
      get :reset
    end
    member do
      patch :toggle_readable
      patch :toggle_purpose
      patch :toggle_trust_level
    end
  end
  resources :enrichments, only: [:index, :show, :create, :destroy]
  resources :indicator_contexts
  resources :vulnerabilities do
    get :autocomplete_vulnerability_codename, :on => :collection, as: :autocomplete
    collection do
      match 'search' => 'vulnerabilities#search', via: [:get, :post], as: :search
      get :new_import
      post :create_import
    end
    member do
      patch :toggle_processed
      patch :toggle_custom_relevance
      patch :toggle_readable
    end
  end
  resources :custom_fields
  resources :delivery_lists
  resources :delivery_subjects, only: [:index, :create, :destroy] do
    collection do
      get 'list_subjects'
      post 'notify' => 'delivery_subjects#notify', via: [:get], as: :notify
    end
    member do
      patch :toggle_readable
    end
  end
  resources :delivery_recipients, only: [:index, :create, :destroy]
  resources :search_filters
  resources :vulnerability_kinds
  resources :vulnerability_bulletin_kinds
  resources :vulnerability_bulletins do
    collection do
      patch :toggle_subscription
    end
    member do
      patch :toggle_readable
      patch :publicate
    end
  end
  resources :vulnerability_bulletin_members, only: %i[index create destroy]
  resources :vulnerability_bulletin_statuses

  resources :user_actions, only: [:index, :show]

  post '/translatet', to: 'translate#show', as: :translate

  resources :notifications_logs, only: [:index]

  resources :selectors, only: [:index]

  patch(
    '/selectors',
    to: 'selectors#update',
    as: :toggle_selection
  )
  delete(
    '/reset_selections',
    to: 'selectors#destroy',
    as: :reset_selections
  )

  patch(
    '/toggle_processed_processing_logs',
    to: 'processing_logs#toggle_processed',
    as: :toggle_processed_processing_logs
  )

  resources :custom_reports
  resources :custom_reports_folders do
    collection do
      post :paste
    end
  end

  resources :custom_reports_results, only: [:index, :show, :new, :create, :destroy, :download] do
    member do
      get 'download'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :custom_reports_api, only: [:show]
      resources :ra_api, only: [:create]
    end
  end

  resources :agents

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminSidekiqWebConstraint.new
  require 'sidekiq/cron/web'

  # TODO: use or delete (it for routing error handling when api client used)
  # match '*path', to: "api/v1/routing_error#show", format: true, constraints: {format: :json}, defaults: {format: 'html'}, via: [:get, :post]
end

app/models/custom_report.rb
class CustomReport < ApplicationRecord
  include OrganizationMember
  include Linkable
  include Tagable
  include Attachable
  include Rightable

  RESULT_FORMATS = {
    csv: 'csv',
    json: 'json'
  }.freeze

  enum result_format: RESULT_FORMATS, _prefix: true

  after_destroy :delete_result_folder

  validates :name, length: { minimum: 3, maximum: 300 }
  validates :name, uniqueness: { scope: [:folder_id, :result_format] }
  validates :organization_id, numericality: { only_integer: true }
  validates :folder_id, numericality: { only_integer: true, allow_blank: true }
  validates :result_format, inclusion: { in: CustomReport.result_formats.values }
  validates :statement, presence: true

  validate :statement_danger_commands

  belongs_to :custom_reports_folder, foreign_key: :folder_id, optional: true
  belongs_to :organization
  has_many :custom_reports_results, dependent: :destroy

  has_one :schedule, as: :job, dependent: :destroy

  def encoding
    return 'UTF-8' if utf_encoding?
    'Windows-1251'
  end

  def variables_arr
    CustomReportJob::Query.new(custom_report.statement).variables_arr
  end

  def worker
    'CustomReportJob'
  end

  def job_queue
    'custom_report'
  end

  def last_result
    custom_reports_results.last
  end

  def result_storage_dir
    Rails.root.join(
      'file_storage',
      'custom_reports',
      id.to_s
    )
  end

  private

  def delete_result_folder
    dir = result_storage_dir
    FileUtils.rm_rf(dir) if File.directory?(dir)
  end

  def statement_danger_commands
    return unless statement.match? /\b(drop|delete|update|create|alter|grant|load|insert|lock|reindex|set|truncate)\b/i
    errors.add(:statement, 'Danger SQL commands can`t be used!')
  end
end

app/controllers/custom_reports_controller.rb
# frozen_string_literal: true

class CustomReportsController < ApplicationController
  include RecordOfOrganization

  before_action :set_folder, only: [:new, :create, :edit, :update, :destroy]

  private

  def set_folder
#    id = if params[:folder_id]
#           params[:folder_id]
#         elsif params.dig(:custom_report, :folder_id)
#           params[:custom_report][:folder_id]
#         end
    id = params[:folder_id] || params.dig(:custom_report, :folder_id)
    @folder = CustomReportsFolder.where(id: id).first || OpenStruct.new(id: nil)
  end

  def model
    CustomReport
  end

  def default_sort
    'created_at desc'
  end

  def records_includes
    %i[organization]
  end
end

app/views/custom_reports/_form.html.slim
.well
  = render 'form_errors', record: @record
  .row
    = form_for @record, html: {class: 'form-horizontal'} do |f|

      = f.hidden_field :folder_id, value: @record&.folder_id || @folder.id

      .form-group.required
        .field
          .col-lg-2.text-right
            = f.label :organization_id, class: 'control-label'
          .col-lg-8
            = autocomplete_field_tag(:organization,
              '',
              autocomplete_organizations_path,
              id_element: '#custom_report_organization_id',
              class: 'form-control',
              autocomplete: :off,
              value: (@record.organization&.name || current_user.organization.name),
              placeholder: t('placeholders.auto'))
            = f.hidden_field :organization_id, value: (@record.organization_id || current_user.organization_id)

      .form-group.required
        .field
          .col-lg-2.text-right
            = f.label :name, class: 'control-label'
          .col-lg-8
            = f.text_field :name, class: 'form-control'

      .form-group.required
        .field
          .col-lg-2.text-right
            = f.label :result_format, class: 'control-label'
          .col-lg-8
            = f.select(:result_format,
              CustomReport.result_formats.keys.collect { |format| [CustomReport.human_enum_name(:result_format, format), format] },
              { selected: @record.result_format || :csv },
              class: 'form-control')

      .form-group
        .col-lg-offset-2.col-lg-8
          .checkbox
             label
               = f.check_box :add_csv_header, class: 'big-checkbox'
               strong
                 | #{t('activerecord.attributes.custom_report.add_csv_header')}

      .form-group
        .col-lg-offset-2.col-lg-8
          .checkbox
             label
               = f.check_box :utf_encoding, class: 'big-checkbox'
               strong
                 | #{t('activerecord.attributes.custom_report.utf_encoding')}

      .form-group
        .field
          .col-lg-2.text-right
            = f.label :description, class: 'control-label'
          .col-lg-8
            = f.text_area :description, rows: 4, class: 'form-control'

      .form-group.required
        .field
          .col-lg-2.text-right
            = f.label :statement, class: 'control-label'
          .col-lg-8
            = f.text_area :statement, rows: 12, class: 'form-control'

      .actions.form-group
        .col-lg-offset-2.col-lg-8
          => f.submit t('helpers.submit.save'), class: 'btn btn-success'
          = render 'form_back_button'

app/views/custom_reports/_record.html.slim
= show_for @record do |r|
  = r.show :name
  = r.show :id
  = r.show(:organization_id,
    value: link_to(@record.organization.name,
    @record.organization))
  = r.show :folder_id, value: @record.custom_reports_folder&.name
  - if current_user.admin_editor? || current_user.can?(:edit, @record.class)
    = r.show :statement
  = r.show :result_format
  = r.show :add_csv_header
  = r.show :encoding
  = r.show :description

= render 'application/record_versions'

=> link_to custom_reports_folders_path(folder_id: @record.folder_id) do
  span.btn.btn-default
    => fa_icon 'code-fork'
    = CustomReportsFolder.model_name.human

app/views/custom_reports/_records.html.slim
= index_search :name_or_organization_name_cont
= index_for records do |t|
  - t.header attribute: :name, sort: :desc
  - t.header attribute: :id, sort: :desc
  - t.header attribute: :organization_id, sort: :desc
  - t.field { |record| link_to record.name, record, class: 'btn btn-link' }
  - t.field { |record| link_to record.id, record, class: 'btn btn-link' }
  - t.field { |record| link_to(record.organization&.name, record.organization) }

app/views/custom_reports/_show_tabs.html.slim
=  tabs active_tab, :main_info, from_external_link do |tabs|
  - tabs.add(:main_info, polymorphic_path(record, active_tab: :main_info)) do
    = t('navigations.main_info')
  - tabs.add(:custom_reports_results, custom_reports_results_path(custom_report_id: record.id), 'CustomReportsResult', true) do
    = CustomReportsResult.model_name.human(count: 2)
  - tabs.add(:schedule, schedule_path(job_id: record.id, job_type: 'CustomReport'), 'Schedule', true) do
    = fa_icon 'clock-o'
    =< Schedule.model_name.human(count: 1)
  - tabs.add(:links, polymorphic_path(record, active_tab: :links), 'Link') do
    = fa_icon 'link'
    =< Link.model_name.human(count: 2)
  - tabs.add(:tags, polymorphic_path(record, active_tab: :tags), 'Tag') do
    = fa_icon 'tags'
    =< Tag.model_name.human(count: 2)
  - tabs.add(:files, polymorphic_path(record, active_tab: :files), 'AttachedFile') do
    = fa_icon 'folder'
    =< AttachedFile.model_name.human(count: 2)